### ISSUE TITLE
Container Crashing

### ISSUE THREAD

**Issue by HrKnuddel** [hhansen06/gameTTS#1]
[https://github.com/lexkoro/GameTTS/releases/download/v0.0.1/G_600000.pth](https://github.com/lexkoro/GameTTS/releases/download/v0.0.1/G_600000.pth) gives a 404 and that crashes the Container

**Comment by hhansen06** [comment]
i embedded the voice model into the repo. should work now.

**Comment by HrKnuddel** [comment]
Nothing changed... Maybe forgot to push or build something?

**Comment by hhansen06** [comment]
had issues with github and big files. now the container is working again.

**Comment by HrKnuddel** [comment]
It works fine when building it myself like in the readme, but the image still not working with this error: 
`Traceback (most recent call last):

  File "/usr/src/app/GameTTS/main.py", line 16, in \<module>

    synthesizer = Synthesizer(TTS_CONFIG_PATH)

  File "/usr/src/app/GameTTS/vits/synthesizer.py", line 17, in \_\_init\_\_

    self.hps_config = self.load_config(config_path)

  File "/usr/src/app/GameTTS/vits/synthesizer.py", line 48, in load_config

    return utils.get_hparams_from_file(conf_path)

  File "/usr/src/app/GameTTS/vits/utils.py", line 179, in get_hparams_from_file

    with open(config_path, "r") as f:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/GameTTS/vits/model/config.json'`
(sometimes i hate this weird formating)

**Comment by hhansen06** [comment]
which image are you using? henrikhansen/gametts should work ?

**Comment by HrKnuddel** [comment]
that is exactly that image... i toke the docker-compose.yml and put it in portainer and changed the volume path, to match the path where i pulled the repo and replaced the build line with the image.

**Comment by HrKnuddel** [comment]
Here is the compose i use:
```
version: '3'

volumes:
  gametts:

services:
  gametts:
    image: henrikhansen/gametts
    restart: always
    ports:
      - 5000:5000
      
    volumes:
      - /opt/gameTTS:/usr/src/app/GameTTS/vits/model/
```

**Comment by HrKnuddel** [comment]
I had to revert to a backup of my server for other reason and after i repulled the image it worked!
